/* Generated By:JavaCC: Do not edit this line. MaximaParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MaximaParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NAME = 5;
  /** RegularExpression Id. */
  int NUMBER = 6;
  /** RegularExpression Id. */
  int OPEN_BRACKET = 7;
  /** RegularExpression Id. */
  int CLOSE_BRACKET = 8;
  /** RegularExpression Id. */
  int EQUALS = 9;
  /** RegularExpression Id. */
  int COMMA = 10;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "<NAME>",
    "<NUMBER>",
    "\"[\"",
    "\"]\"",
    "\"=\"",
    "\",\"",
  };

}
