/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LAMBDA = 5;
  /** RegularExpression Id. */
  int PLUS = 6;
  /** RegularExpression Id. */
  int MINUS = 7;
  /** RegularExpression Id. */
  int DIVIDEBY = 8;
  /** RegularExpression Id. */
  int TIMES = 9;
  /** RegularExpression Id. */
  int OPERATOR = 10;
  /** RegularExpression Id. */
  int NAME = 11;
  /** RegularExpression Id. */
  int NUMBER = 12;
  /** RegularExpression Id. */
  int OPEN_PAREN = 13;
  /** RegularExpression Id. */
  int CLOSE_PAREN = 14;
  /** RegularExpression Id. */
  int OPEN_BRACKET = 15;
  /** RegularExpression Id. */
  int CLOSE_BRACKET = 16;
  /** RegularExpression Id. */
  int EQUALS = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"lambda\"",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\"*\"",
    "<OPERATOR>",
    "<NAME>",
    "<NUMBER>",
    "<OPEN_PAREN>",
    "<CLOSE_PAREN>",
    "\"[\"",
    "\"]\"",
    "\"=\"",
  };

}
